### ISSUE TITLE
[BUG]: Buffer missing

### ISSUE THREAD

**Issue by Chaostheorie** [AhmedMKamal/cookie-api#2]
Thank you for your excellent work on this package. It's really useful for development and helps me a lot. It's really appreciated seeing such a high quality of code.

After testing your module in my application, I noticed that when using `setCookie` the library tries to access `Buffer`. This made the function unusable when called from a browser since `Buffer` is a class native to node. ([Similar Issue](https://stackoverflow.com/questions/41198793/buffer-not-found-in-node-js-browser-code))

The solution for the above-mentioned issue was using an alternative Buffer, like [buffer](https://www.npmjs.com/package/buffer), As far as I can tell this should also be able to solve the issue here.

**Comment by Chaostheorie** [comment]
Thank you for the quick response and fix. Unfortunately your fix misses adding the `buffer` dependency. When using this module (specifically anything from 'api.ts').  I've made an altering version without Buffer and instead relying on [`btoa/ atoa`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa#unicode_strings) for encoding.

**Comment by ahmedkamalio** [comment]
@Chaostheorie Can you open a PR with your fix, please?
